# cSpell: disable

# compound root
compound_root_patterns = [
    r'(tam tam)',
    r'(toruk makto[\w]*)',
    r'(tsko[\w]* swizaw[\w]*)',
    r'(tsawl sl[\w]*u)',
    r'(eltu[\w]* lefngap)',
    r'(pängkxoyu[\w]* lekoren)',
    r'(tìftia[\w]* kifkeyä)',
    r'(way[\w]* a plltxe)',
    r'(way[\w]* a rol)',
    r"(wayä aylì'u[\w]*)",
    r'(uvan[\w]* letokx)',
    r'(rel[\w]* arusikx)',
    r'(tìftiatu[\w]* kifkeyä)',
    r'(swoasey[\w]* ayll)',
    r'(yomyo[\w]* lerìk)',
    r"(mo[\w]* a fngä')",
    r'(tsw[\w]*ìk kxenerit)',
    r'(txopu sl[\w]*eyk[\w]*u)',
    r'(to tìtseri)',
    r'(pamrelvul[\w]* lerìn)',
    r'(Nìyu Yorkì[\w]*)',
    r'(ayRam[\w]* aLusìng)',
    r'(ayVitrayä Ramunong)',
    r'(Pongu Pongu[\w]*)',
    r'(Swotu[\w]* Wayä)',
    r'(Utral[\w]* Aymokriyä)',
    r'(koren[\w]* ayll)',
    r"(txe'lanti wrrz[\w]*är[\w]*ìp)",
    r"(tìpe'ngayt wrrz[\w]*eykär[\w]*ìp)",
    r"(tìpe'ngayt wrrz[\w]*är[\w]*ìp)",
    r'(zam mì zam)',
    r'(krro krro)'
]

# ____ si verbs
si_verb_patterns = [
    r'(tìsraw s[\w]*eyk[\w]*i)',
    r'(win säp[\w]*i)',
    r'(lew säp[\w]*i)',
    r'(piak säp[\w]*i)',
    r'(tstu säp[\w]*i)',
    r'(ioi säp[\w]*i)',
    r'(ätxäle s[\w]*i)',
    r'(eltu s[\w]*i)',
    r'(kelku s[\w]*i)',
    r'(lrrtok s[\w]*i)',
    r'(nari s[\w]*i)',
    r'(uvan s[\w]*i)',
    r'(zoplo s[\w]*i)',
    r'(kavuk s[\w]*i)',
    r'(lew s[\w]*i)',
    r'(muntxa s[\w]*i)',
    r'(piak s[\w]*i)',
    r"(tì'awm s[\w]*i)",
    r'(tìkangkem s[\w]*i)',
    r'(tìsraw s[\w]*i)',
    r'(tsaheyl s[\w]*i)',
    r"(tsap'alute s[\w]*i)",
    r'(tstu s[\w]*i)',
    r'(win s[\w]*i)',
    r'(srung s[\w]*i)',
    r'(txopu s[\w]*i)',
    r'(pamrel s[\w]*i)',
    r'(ultxa s[\w]*i)',
    r'(yemfpay s[\w]*i)',
    r'(tìkxey s[\w]*i)',
    r'(kxll s[\w]*i)',
    r'(tsulfä s[\w]*i)',
    r'(teya s[\w]*i)',
    r'(kem s[\w]*i)',
    r'(irayo s[\w]*i)',
    r'(eltur tìtxen s[\w]*i|tìtxen s[\w]*i)',
    r'(law s[\w]*i)',
    r'(kaltxì s[\w]*i)',
    r'(tskxekeng s[\w]*i)',
    r'(way s[\w]*i)',
    r'(tìhawnu s[\w]*i)',
    r"(kìte'e s[\w]*i)",
    r"('en s[\w]*i)",
    r'(pamtseo s[\w]*i)',
    r'(hasey s[\w]*i)',
    r'(tìftang s[\w]*i)',
    r'(skxir s[\w]*i)',
    r'(ftxozä s[\w]*i)',
    r'(ioi s[\w]*i)',
    r"(rì'ìr s[\w]*i)",
    r'(ngampam s[\w]*i)',
    r'(leioae s[\w]*i)',
    r"(säro'a s[\w]*i)",
    r'(syeha s[\w]*i)',
    r'(slantire s[\w]*i)',
    r'(kangay s[\w]*i)',
    r'(fta s[\w]*i)',
    r'(oìsss s[\w]*i)',
    r"(sä'eoio s[\w]*i)",
    r'(yak s[\w]*i)',
    r'(mowar s[\w]*i)',
    r'(tìkxìm s[\w]*i)',
    r'(kxap s[\w]*i)',
    r'(unil s[\w]*i)',
    r'(tìmungwrr s[\w]*i)',
    r'(tìnvi s[\w]*i)',
    r'(stiwi s[\w]*i)',
    r'(laro s[\w]*i)',
    r'(kxu s[\w]*i)',
    r'(ekxan s[\w]*i)',
    r'(afpawng s[\w]*i)',
    r'(fwìng s[\w]*i)',
    r'(lie s[\w]*i)',
    r'(liswa s[\w]*i)',
    r'(meuia s[\w]*i)',
    r'(tswesya s[\w]*i)',
    r"('on s[\w]*i)",
    r'(leyr s[\w]*i)',
    r'(lesar s[\w]*i)',
    r"('asap s[\w]*i)",
    r'(txansngum s[\w]*i|sngum s[\w]*i)',
    r"(stä'nìpam s[\w]*i)",
    r'(tsaktap s[\w]*i)',
    r'(tstunkem s[\w]*i)',
    r'(sänume s[\w]*i)',
    r'(äzan s[\w]*i)',
    r'(kemuia s[\w]*i)',
    r'(voìk s[\w]*i)',
    r'(tìzin s[\w]*i)',
    r'(tìkezin s[\w]*i)',
    r'(tsantxäl s[\w]*i)',
    r'(henga s[\w]*i)',
    r"(lì'fyeng s[\w]*i)"
]

# tìng ____ verbs
ting_verb_patterns = [
    r'(t[\w]*ìng mikyun)',
    r'(t[\w]*ìng nari)',
    r'(t[\w]*ìng tseng)',
    r'(t[\w]*ìng lawr)',
    r'(t[\w]*ìng zekwä)',
    r'(t[\w]*ìng ontu)',
    r'(t[\w]*ìng ftxì)',
    r'(t[\w]*ìng syawn)'
]

patterns = compound_root_patterns + si_verb_patterns + ting_verb_patterns
